// Home Types 
export const FETCH_HOME_REQUEST = 'FETCH_HOME_REQUEST'
export const FETCH_HOME_SUCCESS = 'FETCH_HOME_SUCCESS'
export const FETCH_HOME_FAILURE = 'FETCH_HOME_FAILURE'


// mycontest Types

export const FETCH_MYCONTEST_REQUEST = 'FETCH_MYCONTEST_REQUEST'
export const FETCH_MYCONTEST_SUCCESS = 'FETCH_MYCONTEST_SUCCESS'
export const FETCH_MYCONTEST_FAILURE = 'FETCH_MYCONTEST_FAILURE'

// user Types

export const FETCH_USER_REQUEST = 'FETCH_USER_REQUEST'
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS'
export const FETCH_USER_FAILURE = 'FETCH_USER_FAILURE'

// App Reminder Types

export const FETCH_APPREMINDER_SUCCESS = 'FETCH_APPREMINDER_SUCCESS'

//Game Switcher Types

export const FETCH_GameSwitcher_SUCCESS= 'FETCH_GameSwitcher_SUCCESS'


// Drawer Switcher 

export const FETCH_DRAWERSWITCHER_SUCCESS= 'FETCH_DRAWERSWITCHER_SUCCESS'